name: LBChatFilter
main: LBChatFilter\Main
version: 0.0.1
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
load:
author: LBSG
description: Lifeboat ChatFilter Plugin For All
website: https://lbsg.net
commands:
 lbchatfilter:
  description: "Manages LBChatFilter"
  aliases: [cf, chatfilter]
  usage: "/lbchatfilter <command> <args>"
  permission: lbchatfilter
permissions:
 lbchatfilter:
  default: op
  description: "Commands that handle all ChatFilter things"
